CREATE SCHEMA IF NOT EXISTS portfolio;
REVOKE ALL ON SCHEMA portfolio FROM PUBLIC, anon, authenticated;
SET search_path TO portfolio;
CREATE TABLE IF NOT EXISTS projects (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, category TEXT NOT NULL, summary TEXT NOT NULL,
 details TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '', url TEXT NOT NULL DEFAULT '',
 image TEXT NOT NULL DEFAULT '', published INTEGER NOT NULL DEFAULT 0, position INTEGER NOT NULL DEFAULT 0,
 updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);
CREATE TABLE IF NOT EXISTS jobs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, client TEXT NOT NULL, fee_cents INTEGER NOT NULL CHECK(fee_cents>=0),
 status TEXT NOT NULL DEFAULT 'active', notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);
CREATE TABLE IF NOT EXISTS invoices (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id INTEGER NOT NULL REFERENCES jobs(id), number TEXT NOT NULL UNIQUE,
 issue_date TEXT NOT NULL, due_date TEXT NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents>0),
 description TEXT NOT NULL DEFAULT '', void INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);
CREATE TABLE IF NOT EXISTS payments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, invoice_id INTEGER NOT NULL REFERENCES invoices(id), date TEXT NOT NULL,
 amount_cents INTEGER NOT NULL CHECK(amount_cents>0), method TEXT NOT NULL, reference TEXT NOT NULL DEFAULT '',
 notes TEXT NOT NULL DEFAULT '', void INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);
CREATE TABLE IF NOT EXISTS expenses (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date TEXT NOT NULL, payee TEXT NOT NULL, category TEXT NOT NULL,
 amount_cents INTEGER NOT NULL CHECK(amount_cents>0), business_percent INTEGER NOT NULL CHECK(business_percent BETWEEN 0 AND 100),
 reference TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', void INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);
CREATE TABLE IF NOT EXISTS audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, recorded_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text), action TEXT NOT NULL,
 entity TEXT NOT NULL, entity_id INTEGER, before_json TEXT, after_json TEXT
);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, csrf TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_invoices_job ON invoices(job_id);
CREATE INDEX IF NOT EXISTS idx_payments_invoice ON payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON payments(date);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date);

CREATE TABLE IF NOT EXISTS login_attempts (bucket TEXT NOT NULL, attempted_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_attempts_time ON login_attempts(attempted_at);
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['projects','jobs','invoices','payments','expenses','audit','sessions','login_attempts'] LOOP
    EXECUTE format('ALTER TABLE portfolio.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON portfolio.%I FROM PUBLIC, anon, authenticated', t);
  END LOOP;
END $$;
INSERT INTO storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
VALUES ('portfolio-images','portfolio-images',false,3145728,ARRAY['image/jpeg','image/png','image/webp'])
ON CONFLICT (id) DO NOTHING;
